package dmacc_test

// The ratchet: the tree's committed size and cycle figures, verified
// EXACTLY on every `make test` run (prompts/042 §8).
//
// The emulator is deterministic, so a figure that moves at all moved
// because something in the compiler, the assembler or the target
// source moved. Both directions fail: a regression is obviously worth
// a stop, and an unrecorded IMPROVEMENT is worth one too — the number
// is what the next round measures against, and a wave that quietly
// banked 3% is a wave nobody reported.
//
// The table is testdata/ratchet.txt, one `key<TAB>value` line per
// figure, sorted, so a regeneration diffs as the set of numbers that
// actually moved. Regenerate with
//
//	make ratchet                  (sizes + the xsh cycle table)
//	make ratchet DMACC_BENCH=1    (… and the heavy benches too)
//
// A regeneration is a MEASUREMENT: report the diff, do not refresh it
// to make a red run green. Figures a run did not measure are carried
// over unchanged, which is what lets the cheap regeneration leave the
// heavy rows alone.

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"testing"
)

const ratchetPath = "testdata/ratchet.txt"

// ratchetHead is the file's own explanation, rewritten with it.
const ratchetHead = `# The size and cycle ratchet (prompts/042 §8). Generated by
# ` + "`make ratchet`" + `; verified exactly by the tests named in the keys.
#
#   size/<image>/<segment>       TestZZAllSizes, bytes
#   deploy/<image>/<segment>     TestDeploySizes, bytes (as shipped)
#   xsh/<command>/<cold|warm>    TestZZBenchXsh, machine cycles
#   vi/<phase>                   TestZZBenchVi, machine cycles      [DMACC_BENCH]
#   fbcon/<board>/<workload>     TestZZBenchFbcon, machine cycles   [DMACC_BENCH]
#   nyancat/<figure>             TestZZBenchNyancat, cycles/frame   [DMACC_BENCH]
#   game/<figure>                TestGameBench, as printed          [DMACC_BENCH]
#
# Every entry is exact: the emulator is deterministic, so any drift —
# regression OR unrecorded improvement — fails the build. Regenerating
# is a measurement to report, not a golden to refresh.
`

var ratchet struct {
	once sync.Once
	err  error
	mu   sync.Mutex
	want map[string]uint64 // the committed table
	got  map[string]uint64 // what this run measured
}

func genRatchet() bool { return os.Getenv("GEN_RATCHET") != "" }

// heavyRatchet reports whether the DMACC_BENCH-gated figures take part
// in this run — they are only measured when their benches run.
func heavyRatchet() bool { return os.Getenv("DMACC_BENCH") != "" }

func loadRatchet() {
	ratchet.once.Do(func() {
		ratchet.want, ratchet.got = map[string]uint64{}, map[string]uint64{}
		b, err := os.ReadFile(ratchetPath)
		if os.IsNotExist(err) && genRatchet() {
			return // seeding a table from nothing
		}
		if err != nil {
			ratchet.err = err
			return
		}
		for n, line := range strings.Split(string(b), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			k, v, ok := strings.Cut(line, "\t")
			if !ok {
				ratchet.err = fmt.Errorf("%s:%d: no tab in %q", ratchetPath, n+1, line)
				return
			}
			u, err := strconv.ParseUint(strings.TrimSpace(v), 10, 64)
			if err != nil {
				ratchet.err = fmt.Errorf("%s:%d: %v", ratchetPath, n+1, err)
				return
			}
			ratchet.want[k] = u
		}
	})
}

// ratchetDrift is the message one moved figure produces. Split out so
// the drift path itself is testable without a red build
// (TestRatchetCatchesDrift).
func ratchetDrift(key string, got, want uint64, known bool) error {
	if !known {
		return fmt.Errorf("ratchet %s = %d: no such figure in %s. A new figure is "+
			"recorded with `make ratchet`", key, got, ratchetPath)
	}
	if got == want {
		return nil
	}
	dir := "REGRESSED"
	if got < want {
		dir = "improved"
	}
	return fmt.Errorf("ratchet %s = %d, %s says %d (%s by %+d, %+.2f%%). "+
		"If the move is intended, regenerate with `make ratchet` and report it; "+
		"otherwise this is a regression to explain",
		key, got, ratchetPath, want, dir, int64(got)-int64(want),
		100*(float64(got)-float64(want))/float64(want))
}

// pinSet verifies a whole group of figures at once: under GEN_RATCHET
// it records them, otherwise every key must be in the table with the
// same value AND the table must hold no other key with that prefix, so
// a deleted or renamed figure fails as loudly as a moved one.
func pinSet(t *testing.T, prefix string, got map[string]uint64) {
	t.Helper()
	loadRatchet()
	if ratchet.err != nil {
		t.Fatalf("ratchet: %v", ratchet.err)
	}
	ratchet.mu.Lock()
	for k, v := range got {
		if !strings.HasPrefix(k, prefix) {
			t.Errorf("ratchet: %q does not belong to the %q group", k, prefix)
		}
		ratchet.got[k] = v
	}
	ratchet.mu.Unlock()
	if genRatchet() {
		t.Logf("ratchet: recorded %d %s figures", len(got), prefix)
		return
	}
	keys := make([]string, 0, len(got))
	for k := range got {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		v, known := ratchet.want[k]
		if err := ratchetDrift(k, got[k], v, known); err != nil {
			t.Error(err)
		}
	}
	for k := range ratchet.want {
		if strings.HasPrefix(k, prefix) {
			if _, ok := got[k]; !ok {
				t.Errorf("ratchet: %s holds %s = %d, which this run did not "+
					"measure — a renamed or deleted figure needs `make ratchet`",
					ratchetPath, k, ratchet.want[k])
			}
		}
	}
}

// writeRatchet rewrites the table: what this run measured, plus every
// figure it did not (so the cheap regeneration leaves the heavy rows
// alone), sorted.
func writeRatchet() error {
	loadRatchet()
	if ratchet.err != nil {
		return ratchet.err
	}
	ratchet.mu.Lock()
	defer ratchet.mu.Unlock()
	out := make(map[string]uint64, len(ratchet.want))
	for k, v := range ratchet.want {
		out[k] = v
	}
	for k, v := range ratchet.got {
		out[k] = v
	}
	keys := make([]string, 0, len(out))
	for k := range out {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString(ratchetHead)
	for _, k := range keys {
		fmt.Fprintf(&b, "%s\t%d\n", k, out[k])
	}
	if err := os.WriteFile(ratchetPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("RATCHET wrote %s: %d figures (%d measured this run)\n",
		ratchetPath, len(out), len(ratchet.got))
	return nil
}

func TestMain(m *testing.M) {
	code := m.Run()
	if genRatchet() {
		if err := writeRatchet(); err != nil {
			fmt.Fprintf(os.Stderr, "ratchet: %v\n", err)
			code = 1
		}
	}
	os.Exit(code)
}

// TestRatchetCatchesDrift is the negative test: the drift path,
// exercised in process, so the failure a real regression would produce
// is checked without needing a red run to see it.
func TestRatchetCatchesDrift(t *testing.T) {
	t.Parallel()
	if err := ratchetDrift("size/ls/text", 12512, 12512, true); err != nil {
		t.Errorf("an unmoved figure failed: %v", err)
	}
	for _, c := range []struct {
		got, want uint64
		dir       string
	}{
		{12520, 12512, "REGRESSED"},
		{12504, 12512, "improved"},
	} {
		err := ratchetDrift("size/ls/text", c.got, c.want, true)
		if err == nil {
			t.Fatalf("%d vs %d passed", c.got, c.want)
		}
		msg := err.Error()
		for _, want := range []string{"size/ls/text", c.dir, "make ratchet",
			fmt.Sprint(c.got), fmt.Sprint(c.want)} {
			if !strings.Contains(msg, want) {
				t.Errorf("drift message %q is missing %q", msg, want)
			}
		}
	}
	err := ratchetDrift("size/brand_new/text", 42, 0, false)
	if err == nil || !strings.Contains(err.Error(), "make ratchet") {
		t.Errorf("an unrecorded figure gave %v", err)
	}
}

// TestRatchetTableLoads keeps the table honest on its own terms: it
// parses, and it is sorted and de-duplicated the way the generator
// writes it, so a hand edit that would have been silently reordered by
// the next regeneration is caught here instead.
func TestRatchetTableLoads(t *testing.T) {
	t.Parallel()
	loadRatchet()
	if ratchet.err != nil {
		t.Fatalf("ratchet: %v", ratchet.err)
	}
	if len(ratchet.want) < 20 {
		t.Fatalf("%s holds only %d figures", ratchetPath, len(ratchet.want))
	}
	b, err := os.ReadFile(ratchetPath)
	if err != nil {
		t.Fatal(err)
	}
	var keys []string
	for _, line := range strings.Split(string(b), "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, _, _ := strings.Cut(line, "\t")
		keys = append(keys, k)
	}
	if !sort.StringsAreSorted(keys) {
		t.Errorf("%s is not sorted; run `make ratchet`", ratchetPath)
	}
	for i := 1; i < len(keys); i++ {
		if keys[i] == keys[i-1] {
			t.Errorf("%s: duplicate key %q", ratchetPath, keys[i])
		}
	}
}
