package dmacc_test

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/puhitaku/dma-cpu/host/boards"
	"github.com/puhitaku/dma-cpu/host/emu"
)

// TestGenXshHotPool regenerates host/dmaasm/xshhot_gen.go — the
// profiled hot half of the kernel literal pool. It builds a feather
// machine with an UNSPLIT pool (every literal resident, one countable
// range), boots it to the prompt, runs a console workload through the
// fb console (so kfbcon's glyph loops profile too), and marks every
// literal read at loop rate (>= 32 reads) as hot.
//
//	GEN_HOTPOOL=1 go test -count=1 -run TestGenXshHotPool ./host/dmacc/
func TestGenXshHotPool(t *testing.T) {
	if os.Getenv("GEN_HOTPOOL") == "" {
		t.Skip("generator: set GEN_HOTPOOL=1 to regenerate xshhot_gen.go")
	}
	xshPoolSplit = false
	defer func() { xshPoolSplit = true }()
	bd := boards.Feather
	flash := make([]byte, bd.FlashSize)
	m, kernC := buildXshBoard(t, flash, bd)
	// Profile the kernel pool: every literal address (unsplit build:
	// all in kernel data).
	lo, hi := ^uint32(0), uint32(0)
	for _, a := range kernC.LitAddrs {
		if a < lo {
			lo = a
		}
		if a+4 > hi {
			hi = a + 4
		}
	}
	m.Profile(lo, hi)
	// Boot to the prompt (mailbox pump, golden-boot style).
	booted := false
	for i := 0; i < 600 && !booted; i++ {
		if _, err := m.Run(emu.RunConfig{MaxCycles: 5_000_000}); err != nil {
			t.Fatalf("boot: %v\nconsole:\n%s", err, m.ConsoleOut)
		}
		for serviceMailboxAt(m, bd.Scratch+0x10, m.Flash, nil) {
		}
		booted = strings.HasSuffix(string(m.ConsoleOut), "$ ")
	}
	if !booted {
		t.Fatalf("no prompt\nconsole:\n%s", m.ConsoleOut)
	}
	// Workload: exec+pipe+fs+console+fbcon scroll traffic.
	m.FeedConsole("echo pipeflow | cat\rls /dev\rcat README\rfree\recho done\r")
	runScript(t, m, 3_000_000_000)
	counts := m.ProfileCounts()
	var hot []string
	var reads, hotreads uint64
	for k, a := range kernC.LitAddrs {
		c := counts[(a-lo)>>2]
		reads += uint64(c)
		if c >= 32 {
			hot = append(hot, k)
			hotreads += uint64(c)
		}
	}
	sort.Strings(hot)
	var b strings.Builder
	b.WriteString("// Code generated by TestGenXshHotPool (host/dmacc/zz_hotpool_test.go);\n")
	b.WriteString("// regenerate with GEN_HOTPOOL=1 go test -run TestGenXshHotPool ./host/dmacc/.\n")
	b.WriteString("// DO NOT EDIT.\n\npackage dmaasm\n\n")
	b.WriteString("// XSHHotLits is the profiled hot half of the xsh kernel's literal\n")
	b.WriteString("// pool: keys whose words were read at loop rate during an emulated\n")
	b.WriteString("// feather boot + console workload. These stay SRAM-resident under\n")
	b.WriteString("// Options.PoolText; everything else moves to flash rodata.\n")
	fmt.Fprintf(&b, "// Profile: %d/%d literals hot, covering %.1f%% of %d pool reads.\n",
		len(hot), len(kernC.LitAddrs), 100*float64(hotreads)/float64(reads), reads)
	b.WriteString("var XSHHotLits = map[string]bool{\n")
	for _, k := range hot {
		fmt.Fprintf(&b, "\t%q: true,\n", k)
	}
	b.WriteString("}\n")
	if err := os.WriteFile("../dmaasm/xshhot_gen.go", []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
	fmt.Printf("HOTPOOL %d/%d hot, %.1f%% of %d reads covered, resident %d bytes\n",
		len(hot), len(kernC.LitAddrs), 100*float64(hotreads)/float64(reads), reads, 4*len(hot))
}
