// Code generated by TestGenPGO (host/dmacc/zz_pgogen_test.go);
// regenerate with `make pgo`. DO NOT EDIT.

package pgo

// The hot-function sets. With dmacc's Options.OptSize on, a function
// named here keeps the fast four-move comparison protocol; every other
// function's compare sites shrink to the two-record descriptor form.
// Each set is the functions that own the top 97% of the text reads (=
// instruction fetches) the workload made, so the descriptor form lands
// on the code that executes rarely and costs bytes.
//
// Names are IR function names and are NOT validated by dmacc: a board
// that links a different module set (the displayless kernels take the
// fb stub) simply has no function by some of these names.

// KernelHotFuncs: 19 of 93 executed functions, covering 97.2% of the
// 23540389 text reads the workload made.
// Workload: a feather boot to the prompt, the xsh benchmark command set
// run cold and warm, seven frames of nyancat on the framebuffer
// console, then an editing session in vi.
var KernelHotFuncs = map[string]bool{
	"badbuf":       true,
	"bread":        true,
	"clear_cells":  true,
	"cons_poll":    true,
	"cputc":        true,
	"cputc_wire":   true,
	"cursor_xor":   true,
	"dma_ksyscall": true,
	"fileread":     true,
	"filewrite":    true,
	"kconswrite":   true,
	"kdmacpy":      true,
	"kdmaset":      true,
	"kfb_condark":  true,
	"kfs_read":     true,
	"kfs_write":    true,
	"lut_build":    true,
	"memmove":      true,
	"readi":        true,
}

// GameHotFuncs: 29 of 84 executed functions, covering 97.2% of the
// 83569659 text reads the workload made.
// Workload: gamepico boot to the menu, menu navigation, then the Dino,
// LANWalk and Yacht scenes played to their first scoring event, and the
// Benchmark run to completion.
var GameHotFuncs = map[string]bool{
	"cell_render":   true,
	"dino_run":      true,
	"frame_sync":    true,
	"gd_wait":       true,
	"gdma_copy":     true,
	"gdma_rows":     true,
	"gdma_spi_rows": true,
	"gfx_blit_runs": true,
	"gfx_damage":    true,
	"gfx_dfill":     true,
	"gfx_text":      true,
	"gfx_text2":     true,
	"gpio_out":      true,
	"in_poll":       true,
	"k_bogo":        true,
	"k_sieve":       true,
	"k_sort":        true,
	"lanwalk_run":   true,
	"led_tick":      true,
	"menu_run":      true,
	"pcm_tick":      true,
	"snd_tick":      true,
	"spi_put8":      true,
	"stick":         true,
	"uputc":         true,
	"uputn":         true,
	"uputs":         true,
	"vline2":        true,
	"xrand":         true,
}
