// Package dmacc compiles LLVM IR (the clang -O1 subset parsed by llir)
// to dmaasm source. It is the back half of the Phase 4 compiler: clang
// lowers C to IR, dmacc lowers IR to the DMA machine.
//
// Model (prompts/overview.md §4.5): there is no register allocator —
// every SSA value, parameter, and phi gets its own SRAM word, because on
// this machine a spill slot costs exactly as much as a register. Frames
// are static (one per function), so v0 rejects recursion; calls follow
// ABI v0 (args r0–r3, result r0, lr saved to a frame word by non-leaf
// callees). Interruptibility: a safepoint is emitted at every backward
// branch unless Options.NoSafepoints.
//
// The output is SKU-portable .dasm; per-SKU encoding happens in dmaasm.
package dmacc

import (
	"fmt"
	"sort"
	"strings"

	"github.com/puhitaku/dma-cpu/llir"
)

// Options configures one compilation.
type Options struct {
	Entry           string // entry function, default "main"
	NoSafepoints    bool   // omit safepoints at backward branches
	InlineCompares  bool   // inline comparison sequences (faster, much larger)
	Stats           *Stats // when non-nil, collect size attribution
}

// Compile translates a parsed module into dmaasm source. The generated
// program calls Entry from a small crt0, stores its i32 result in the
// exported `exitcode` word, and halts.
func Compile(m *llir.Module, opts Options) (string, error) {
	if opts.Entry == "" {
		opts.Entry = "main"
	}
	m.ResolveAliases()
	g := &gen{m: m, opts: opts, rt: map[string]bool{}, cmpUsed: map[string]bool{}}
	if err := g.run(); err != nil {
		return "", err
	}
	return g.out.String(), nil
}

type gen struct {
	m    *llir.Module
	opts Options
	out  strings.Builder

	data strings.Builder // .data lines (after .regs)
	text strings.Builder // .text lines (after crt0)

	rt      map[string]bool // runtime routines needed
	cmpUsed map[string]bool // comparison millicode helpers needed
	stubN   int             // generated label counter
	funcIdx map[string]*llir.Func
	maxVar  map[string]int // variadic callee -> max variadic arg count seen
}

// uartMMIO maps the compiler-known UART globals to dmaasm MMIO operands
// (SKU-resolved at assembly time). C declares them in <dma/mmio.h>.
func uartMMIO(name string) string {
	switch name {
	case "__dma_uart_dr":
		return "%uartdr"
	case "__dma_uart_fr":
		return "%uartfr"
	}
	return ""
}

func (g *gen) run() error {
	g.funcIdx = map[string]*llir.Func{}
	for _, f := range g.m.Funcs {
		g.funcIdx[f.Name] = f
	}
	entry, ok := g.funcIdx[g.opts.Entry]
	if !ok {
		return fmt.Errorf("dmacc: entry function %q is not defined", g.opts.Entry)
	}
	if entry.Ret.Kind != llir.TInt {
		return fmt.Errorf("dmacc: entry function %q must return an integer", g.opts.Entry)
	}
	g.collectGarbage(entry)
	if err := g.checkNoRecursion(); err != nil {
		return err
	}
	// Variadic frames are static too: size each callee's vararg area to
	// the largest call in the whole program.
	g.maxVar = map[string]int{}
	for _, f := range g.m.Funcs {
		for _, b := range f.Blocks {
			for _, ins := range b.Instrs {
				if ins.Op != "call" || ins.Callee == "" {
					continue
				}
				if cf, ok := g.funcIdx[ins.Callee]; ok && cf.Variadic {
					if n := len(ins.Args) - len(cf.Params); n > g.maxVar[ins.Callee] {
						g.maxVar[ins.Callee] = n
					}
				}
			}
		}
	}
	for _, gl := range g.m.Globals {
		if uartMMIO(gl.Name) != "" {
			continue // hardware register, not storage
		}
		if err := g.emitGlobal(gl); err != nil {
			return err
		}
	}
	for _, f := range g.m.Funcs {
		if err := g.emitFunc(f); err != nil {
			return err
		}
	}

	// Assemble the file: header, data, crt0, functions, runtime.
	w := &g.out
	fmt.Fprintf(w, "; generated by dmacc — do not edit\n")
	fmt.Fprintf(w, ".data\n.regs\nexitcode: .word 0\ndone: .word 0\n")
	fmt.Fprintf(w, "sc0: .word 0\nsc1: .word 0\nsc2: .word 0\n")
	w.WriteString(g.data.String())
	fmt.Fprintf(w, "\n.text\n.entry __start\n__start:\n")
	fmt.Fprintf(w, "    move $crtthunk, dispatch\n")
	fmt.Fprintf(w, "    call %s\n", funcSym(g.opts.Entry))
	fmt.Fprintf(w, "    move r0, exitcode\n")
	fmt.Fprintf(w, "    move $1, done\n")
	fmt.Fprintf(w, "    halt\n")
	// crtthunk is exported: kernels use it as the dispatch EOI value.
	fmt.Fprintf(w, "crtthunk:\n    jumpr irqresume\n")
	w.WriteString(g.text.String())
	g.emitCmpHelpers()
	if err := g.emitRuntime(); err != nil {
		return err
	}
	return nil
}

// collectGarbage drops functions and globals not reachable from the
// entry point — linking libc/ll/*.ll must only cost what the program
// uses. Address-taken functions are reached through value references
// and global initializers, so indirect call targets survive.
func (g *gen) collectGarbage(entry *llir.Func) {
	globIdx := map[string]*llir.Global{}
	for _, gl := range g.m.Globals {
		globIdx[gl.Name] = gl
	}
	reached := map[string]bool{}
	var visitFunc func(*llir.Func)
	var visitSym func(string)
	visitSym = func(name string) {
		if reached["s:"+name] {
			return
		}
		reached["s:"+name] = true
		if f, ok := g.funcIdx[name]; ok {
			visitFunc(f)
		}
		if gl, ok := globIdx[name]; ok && gl.Init != nil {
			var walk func(*llir.Init)
			walk = func(in *llir.Init) {
				if in == nil {
					return
				}
				if in.Sym != "" {
					visitSym(in.Sym)
				}
				for _, e := range in.Elems {
					walk(e)
				}
			}
			walk(gl.Init)
		}
	}
	visitFunc = func(f *llir.Func) {
		if reached["f:"+f.Name] {
			return
		}
		reached["f:"+f.Name] = true
		val := func(v *llir.Value) {
			if v != nil && (v.Kind == llir.VGlobal || v.Kind == llir.VFunc) {
				visitSym(v.Name)
			}
		}
		for _, b := range f.Blocks {
			for _, ins := range b.Instrs {
				for _, a := range ins.Args {
					val(a)
				}
				val(ins.CalleeVal)
				for _, e := range ins.Phi {
					val(e.Val)
				}
				if ins.Op == "call" && ins.Callee != "" && !strings.HasPrefix(ins.Callee, "llvm.") {
					visitSym(ins.Callee)
				}
			}
		}
	}
	visitFunc(entry)
	var funcs []*llir.Func
	for _, f := range g.m.Funcs {
		if reached["f:"+f.Name] {
			funcs = append(funcs, f)
		} else {
			delete(g.funcIdx, f.Name)
		}
	}
	g.m.Funcs = funcs
	var globals []*llir.Global
	for _, gl := range g.m.Globals {
		if reached["s:"+gl.Name] {
			globals = append(globals, gl)
		}
	}
	g.m.Globals = globals
}

// checkNoRecursion rejects call-graph cycles: v0 frames are static.
func (g *gen) checkNoRecursion() error {
	const (
		white = 0
		gray  = 1
		black = 2
	)
	color := map[string]int{}
	var visit func(name string, path []string) error
	visit = func(name string, path []string) error {
		f, ok := g.funcIdx[name]
		if !ok {
			return nil // runtime/intrinsic
		}
		switch color[name] {
		case gray:
			return fmt.Errorf("dmacc: recursion is not supported (v0 static frames): %s -> %s",
				strings.Join(path, " -> "), name)
		case black:
			return nil
		}
		color[name] = gray
		for _, b := range f.Blocks {
			for _, ins := range b.Instrs {
				if ins.Op == "call" && !strings.HasPrefix(ins.Callee, "llvm.") {
					if err := visit(ins.Callee, append(path, name)); err != nil {
						return err
					}
				}
			}
		}
		color[name] = black
		return nil
	}
	names := make([]string, 0, len(g.funcIdx))
	for n := range g.funcIdx {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		if err := visit(n, nil); err != nil {
			return err
		}
	}
	return nil
}

// --- Naming ---

func sanitize(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

func funcSym(name string) string   { return "f_" + sanitize(name) }
func globalSym(name string) string { return "g_" + sanitize(name) }

// --- Globals ---

func (g *gen) emitGlobal(gl *llir.Global) error {
	sym := globalSym(gl.Name)
	size := gl.Typ.Size()
	if size == 0 {
		size = 4
	}
	size = (size + 3) &^ 3
	if gl.Init == nil || gl.Init.Zero {
		fmt.Fprintf(&g.data, "%s: .space %d\n", sym, size)
		return nil
	}
	words, err := g.flattenInit(gl.Init)
	if err != nil {
		return fmt.Errorf("global %s: %v", gl.Name, err)
	}
	fmt.Fprintf(&g.data, "%s:", sym)
	for _, w := range words {
		if w.sym != "" {
			if w.off != 0 {
				fmt.Fprintf(&g.data, " .word %s+%d\n", w.sym, w.off)
			} else {
				fmt.Fprintf(&g.data, " .word %s\n", w.sym)
			}
		} else {
			fmt.Fprintf(&g.data, " .word 0x%x\n", w.val)
		}
	}
	return nil
}

type wordSpec struct {
	val uint32
	sym string
	off uint32
}

// flattenInit lays an initializer tree out as little-endian words.
func (g *gen) flattenInit(in *llir.Init) ([]wordSpec, error) {
	var bytes []byte
	var refs map[int]wordSpec // byte offset -> reference word
	refs = map[int]wordSpec{}
	var walk func(in *llir.Init, off int) error
	walk = func(in *llir.Init, off int) error {
		t := in.Typ
		grow := func(n int) {
			for len(bytes) < off+n {
				bytes = append(bytes, 0)
			}
		}
		switch {
		case in.Zero:
			grow(t.Size())
		case in.Str != nil:
			grow(len(in.Str))
			copy(bytes[off:], in.Str)
		case in.Sym != "":
			if off%4 != 0 {
				return fmt.Errorf("pointer initializer at unaligned offset %d", off)
			}
			grow(4)
			sym := globalSym(in.Sym)
			if _, isFn := g.funcIdx[in.Sym]; isFn {
				sym = funcSym(in.Sym)
			}
			refs[off] = wordSpec{sym: sym, off: in.SymOff}
		case in.Elems != nil:
			switch t.Kind {
			case llir.TArray:
				es := t.Elem.Size()
				for i, e := range in.Elems {
					if err := walk(e, off+i*es); err != nil {
						return err
					}
				}
			case llir.TStruct:
				for i, e := range in.Elems {
					if err := walk(e, off+t.FieldOffset(i)); err != nil {
						return err
					}
				}
			default:
				return fmt.Errorf("aggregate initializer for non-aggregate")
			}
			grow(t.Size())
		default: // scalar
			n := t.Size()
			if n > 4 {
				return fmt.Errorf("i64 initializers are not supported")
			}
			grow(n)
			v := in.Int
			for i := 0; i < n; i++ {
				bytes[off+i] = byte(v >> (8 * i))
			}
		}
		return nil
	}
	if err := walk(in, 0); err != nil {
		return nil, err
	}
	for len(bytes)%4 != 0 {
		bytes = append(bytes, 0)
	}
	var out []wordSpec
	for i := 0; i < len(bytes); i += 4 {
		if r, ok := refs[i]; ok {
			out = append(out, r)
			continue
		}
		v := uint32(bytes[i]) | uint32(bytes[i+1])<<8 | uint32(bytes[i+2])<<16 | uint32(bytes[i+3])<<24
		out = append(out, wordSpec{val: v})
	}
	return out, nil
}
